using System.Collections.Generic;
using ARO.NetCore;
using UnityEngine;
using UnityEngine.Rendering;

namespace ARO.World
{
    /// <summary>Converts engine-neutral MeshBuffers (generated by the unit-tested NetCore code) into Unity meshes.</summary>
    public static class MeshUtil
    {
        /// <summary>Builds a mesh with one submesh per NON-EMPTY slot (so empty slots never cost a draw call). `used[i]` is the buffer slot of submesh i.</summary>
        public static Mesh ToMesh(MeshBuffers mb, string name, out int[] used, bool recalculateNormals = true)
        {
            int n = mb.VertexCount; var v = new Vector3[n]; var uv = new Vector2[n];
            for (int i = 0; i < n; i++) { var p = mb.Vertices[i]; v[i] = new Vector3(p.X, p.Y, p.Z); var t = mb.Uvs[i]; uv[i] = new Vector2(t.X, t.Y); }
            var slots = new List<int>();
            for (int s = 0; s < mb.Triangles.Length; s++) if (mb.Triangles[s].Count > 0) slots.Add(s);
            used = slots.ToArray();
            var m = new Mesh { name = name };
            if (n > 65000) m.indexFormat = IndexFormat.UInt32;
            m.vertices = v; m.uv = uv; m.subMeshCount = Mathf.Max(1, used.Length);
            for (int i = 0; i < used.Length; i++) m.SetTriangles(mb.Triangles[used[i]], i, false);
            m.RecalculateBounds();
            if (recalculateNormals && used.Length > 0) m.RecalculateNormals();
            return m;
        }

        /// <summary>One-submesh copy made of the given slots only (used for physics: road markings are paint, not geometry).</summary>
        public static Mesh ToCollisionMesh(MeshBuffers mb, string name, params int[] slots)
        {
            int n = mb.VertexCount; var v = new Vector3[n];
            for (int i = 0; i < n; i++) { var p = mb.Vertices[i]; v[i] = new Vector3(p.X, p.Y, p.Z); }
            var tris = new List<int>();
            foreach (int s in slots) tris.AddRange(mb.Triangles[s]);
            var m = new Mesh { name = name };
            if (n > 65000) m.indexFormat = IndexFormat.UInt32;
            m.vertices = v; m.SetTriangles(tris, 0, true);
            return m;
        }

        public static Material[] Pick(Material[] all, int[] used)
        {
            var r = new Material[used.Length];
            for (int i = 0; i < used.Length; i++) r[i] = all[used[i]];
            return r;
        }

        public static int Triangles(Mesh m)
        {
            long t = 0; for (int i = 0; i < m.subMeshCount; i++) t += m.GetIndexCount(i);
            return (int)(t / 3);
        }
    }
}
